apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: acss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acss
  template:
    metadata:
      labels:
        app: acss
    spec:      
      containers:
      - image: nebulaepyxis/acss.backend.acss:0.0.10
        name: acss
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        env:     
        # EVENT STORE CONFIG 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        # INTERNAL MONGO DB CONFIG
        - name: MONGODB_URL
          value: mongodb://acss-mongo:27017
          value: mongodb://dbacss-0.dbacss:27017,dbacss-1.dbacss:27017,dbacss-2.dbacss:27017?replicaSet=rs0
        - name: MONGODB_DB_NAME
          value: acss
        # JWT CONFIG        
        - name: JWT_PUBLIC_KEY
          value: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6mv0ByMprlVOd2tzyw/+BxOylLOTG5+oLFgaCiQu3RSIoVyDXtK9d2+kSmP2qsDE+wqVFEdpw2HrUXB8vhjUpu0CluzIw4m5v6l6ExHqyQHBWTCrX4Aynb3eQIWDm1B5Z592XYBLC+ZMDCDkUeiy7R4rGZnG7BPieAGP7KpO23Yc3YVe16Xkwewp3KOgMwch3uyjLVLu386qAeRfEd6yoMYjt+n5dJ5Lv9ZE+vod+BXOrlbmar3GLnE+x+c07YQfAk1jG2WRucN2wqmBKvygRz/Z50jMEclUjddH2wiXbBp9g83MDSQna93tOxlnhRmCTkzsRZqSRVb7HzjASIbfFQIDAQAB\n-----END PUBLIC KEY-----
        # API - GATEWAY CONFIG
        - name: GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
          value: gateway-replies-topic-mbe-acss
        - name: REPLY_TIMEOUT
          value: '2000'
        - name: BROKER_TYPE
          value: PUBSUB
        # RESET LOCK INITIALIZE BACKED
        - name: LOCKVERSION
          value: "0.0.0"
        resources:
          requests:
            cpu: "50m"
        
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
      